---
# make sure everything is up to date.
- name: update
  tags: baz
  yum:
    name: "*"
    state: latest
  become: true
#  register: foo
  when:
   - ansible_distribution == 'RedHat'
   - ansible_distribution_major_version == '7'

- name: update
  tags: baz
  dnf:
    name: "*"
    state: latest
  become: true
#  register: foo
  when:
   - ansible_distribution == 'RedHat'
   - ansible_distribution_major_version == '8'

- name: install more stuff for el7
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ more_stuff_el7 }}"
  become: true
  when:
   - ansible_distribution == 'RedHat'
   - ansible_distribution_major_version == '7'

- name: install more stuff for el8
  dnf:
    name: "{{ item }}"
    state: present
  with_items: "{{ more_stuff_el8 }}"
  become: true
  when:
   - ansible_distribution == 'RedHat'
   - ansible_distribution_major_version == '8'

- name: update
  tags: baz
  apt:
   upgrade: yes
   update_cache: yes
  become: true
#  register: foo
  when:
   - ansible_distribution == 'Ubuntu'

- name: install debconf-utils
  tags: jam
  apt:
    name: "debconf-utils"
    state: present
  become: true
  when:
   - ansible_distribution == 'Ubuntu'

- name: set debconf defaults
  tags: jam
  debconf:
    name: "{{ item.name }}"
    question: "{{ item.question }}"
    vtype: "{{ item.vtype }}"
    value: "{{ item.value }}"
  loop:
   - name: 'krb5-config'
     question: "krb5-config/add_servers_realm"
     vtype: string
     value: 'SHARK.COHORTFS.COM'
   - name: 'krb5-config'
     question: "krb5-config/default_realm"
     vtype: string
     value: 'SHARK.COHORTFS.COM'
   - name: 'krb5-config'
     question: "krb5-config/read_conf"
     vtype: boolean
     value: "true"
   - name: 'krb5-config'
     question: "krb5-config/kerberos_servers"
     vtype: string
     value: 'bull.eng.arb.redhat.com'
   - name: 'krb5-config'
     question: "krb5-config/admin_server"
     vtype: string
     value: 'bull.eng.arb.redhat.com'
   - name: 'krb5-config'
     question: "krb5-config/add_servers"
     vtype: boolean
     value: "true"
   - name: 'postfix'
     question: "postfix/main_mailer_type"
     vtype: select
     value: 'No configuration'
  become: true
  when:
   - ansible_distribution == 'Ubuntu'

- name: install more stuff for ubuntu
  tags: jam
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ more_stuff_ubuntu }}"
  become: true
  when:
   - ansible_distribution == 'Ubuntu'

#- name: report
#  tags: baz
#  debug:
#   msg: "{{ foo }}"
