---
# copy over dot, bin
- name: stat mdw bin
  stat:
    path: /home/mdw/bin
  check_mode: no
  register: mdw_bin

- name: stat mdw hgrc
  stat:
    path: /home/mdw/.hgrc
    get_md5: no
  check_mode: no
  register: mdw_hgrc

- name: extract mdw tarballs
  unarchive:
    src: "{{ item }}"
    dest: "/home/mdw"
  with_items: "{{ mdw_tar_files_ubuntu }}"
  become_user: mdw
  become: true
  when:
   - ansible_os_family == 'Debian'
   - not mdw_hgrc.stat.exists or not mdw_bin.stat.exists

- name: extract mdw tarballs
  unarchive:
    src: "{{ item }}"
    dest: "/home/mdw"
  with_items: "{{ mdw_tar_files_centos }}"
  become_user: mdw
  become: true
  when:
   - ansible_os_family == 'RedHat'
   - not mdw_hgrc.stat.exists or not mdw_bin.stat.exists

- name: see if nvi installed
  tags: bar
  stat: path=/usr/bin/nvi
  check_mode: no
  register: nvi_stat

- name: nvi
  tags: bar
  raw: "yum install -y {{ item }}"
  become: true
  with_items: |
   "https://people.redhat.com/~mwatts/bits/nvi-1.81.6-12.el7.centos.x86_64.rpm"
  when:
   - not nvi_stat.stat.exists
   - ansible_os_family == 'RedHat'

- name: nvi
  tags: bar
  apt:
   name: "{{ item }}"
   state: present
  become: true
  with_items:
   - nvi
   - nvi-doc
  when:
   - not nvi_stat.stat.exists
   - ansible_os_family == 'Debian'

- name: update vi alternatives
  tags: bar
  alternatives:
   name: "{{ item.name }}"
   path: "{{ item.path }}"
  when:
   - ansible_os_family == 'Debian'
  loop:
   - { name: 'vi', path: '/usr/bin/nvi' }
   - { name: 'view', path: '/usr/bin/nview' }
   - { name: 'ex', path: '/usr/bin/nex' }
