---
# copy over dot, bin
- name: stat mdw bin
  tags: mdw
  stat:
    path: /home/mdw/bin
  become_user: mdw
  become: true
  check_mode: no
  register: mdw_bin

- name: stat mdw hgrc
  tags: mdw
  stat:
    path: /home/mdw/.hgrc
    get_md5: no
  become_user: mdw
  become: true
  check_mode: no
  register: mdw_hgrc

- name: extract mdw tarballs for ubuntu
  tags: mdw
  unarchive:
    src: "{{ item }}"
    dest: "/home/mdw"
  with_items: "{{ mdw_tar_files_ubuntu }}"
  become_user: mdw
  become: true
  when:
   - ansible_distribution == 'Ubuntu'
   - not mdw_hgrc.stat.exists or not mdw_bin.stat.exists

- name: extract mdw tarballs for debian
  tags: mdw
  unarchive:
    src: "{{ item }}"
    dest: "/home/mdw"
  with_items: "{{ mdw_tar_files_deb }}"
  become_user: mdw
  become: true
  when:
   - ansible_distribution == 'Debian'
   - not mdw_hgrc.stat.exists or not mdw_bin.stat.exists

- name: extract mdw tarballs for el7
  tags: mdw
  unarchive:
    src: "{{ item }}"
    dest: "/home/mdw"
  with_items: "{{ mdw_tar_files_el7 }}"
  become_user: mdw
  become: true
  when:
   - ansible_os_family == 'RedHat'
   - ansible_distribution_major_version == '7'
   - not mdw_hgrc.stat.exists or not mdw_bin.stat.exists

- name: extract mdw tarballs for el8
  tags: mdw
  unarchive:
    src: "{{ item }}"
    dest: "/home/mdw"
  with_items: "{{ mdw_tar_files_el8 }}"
  become_user: mdw
  become: true
  when:
   - ansible_os_family == 'RedHat'
   - ansible_distribution_major_version == '8'
   - not mdw_hgrc.stat.exists or not mdw_bin.stat.exists

- name: extract mdw tarballs for el9
  tags: mdw
  unarchive:
    src: "{{ item }}"
    dest: "/home/mdw"
  with_items: "{{ mdw_tar_files_el9 }}"
  become_user: mdw
  become: true
  when:
   - ansible_os_family == 'RedHat'
   - ansible_distribution_major_version == '9'
   - not mdw_hgrc.stat.exists or not mdw_bin.stat.exists

- name: extract mdw tarballs for fedora
  tags: mdw
  unarchive:
    src: "{{ item }}"
    dest: "/home/mdw"
  with_items: "{{ mdw_tar_files_fc }}"
  become_user: mdw
  become: true
  when:
   - ansible_os_family == 'RedHat'
   - ansible_distribution == 'Fedora'
   - not mdw_hgrc.stat.exists or not mdw_bin.stat.exists

- name: see if nvi installed
  tags: bar
  stat: path=/usr/bin/nvi
  check_mode: no
  register: nvi_stat

- name: nvi
  tags: bar
  raw: "yum install -y {{ nvi_el7 }}"
  become: true
  when:
   - not nvi_stat.stat.exists
   - ansible_os_family == 'RedHat'
   - ansible_distribution_major_version == '7'

- name: nvi el8
  tags: bar
  raw: "yum install -y {{ nvi_el8 }}"
  become: true
  when:
   - not nvi_stat.stat.exists
   - ansible_os_family == 'RedHat'
   - ansible_distribution_major_version == '8'

- name: nvi el9
  tags: bar
  raw: "yum install -y {{ nvi_el9 }}"
  become: true
  when:
   - not nvi_stat.stat.exists
   - ansible_os_family == 'RedHat'
   - ansible_distribution_major_version == '9'

- name: install nvi for fedora
  tags: bar
  dnf:
   name: "{{ nvi_fed }}"
   disable_gpg_check: yes
   state: present
  become: true
  when:
   - not nvi_stat.stat.exists
   - ansible_os_family == 'RedHat'
   - ansible_distribution == 'Fedora'

- name: install nvi for debian
  tags: bar
  apt:
   name:
   - nvi
   - nvi-doc
   state: present
  become: true
  when:
   - not nvi_stat.stat.exists
   - ansible_distribution_file_variety == 'Debian'

- name: update vi alternatives
  tags: bar
  alternatives:
   name: "{{ item.name }}"
   path: "{{ item.path }}"
  become: true
  when:
   - ansible_distribution_file_variety == 'Debian'
  loop:
   - { name: 'vi', path: '/usr/bin/nvi' }
   - { name: 'view', path: '/usr/bin/nview' }
   - { name: 'ex', path: '/usr/bin/nex' }

- name: see if rcs installed
  tags: bar
  stat: path=/usr/bin/rcs
  check_mode: no
  register: rcs_stat

- name: rcs
  tags: bar
  raw: "dnf install -y {{ rcs_el8 }}"
  become: true
  when:
   - not rcs_stat.stat.exists
   - ansible_os_family == 'RedHat'
   - ansible_distribution_major_version == '8'

- name: see if lynx installed
  tags: bar
  stat: path=/usr/bin/lynx
  check_mode: no
  register: lynx_stat

- name: lynx
  tags: bar
  raw: "dnf install -y {{ lynx_el8 }}"
  become: true
  when:
   - not lynx_stat.stat.exists
   - ansible_os_family == 'RedHat'
   - ansible_distribution_major_version == '8'

- name: rcs
  tags: bar
  raw: "dnf install -y {{ rcs_el9 }}"
  become: true
  when:
   - not rcs_stat.stat.exists
   - ansible_os_family == 'RedHat'
   - ansible_distribution_major_version == '9'

- name: see if lynx installed
  tags: bar
  stat: path=/usr/bin/lynx
  check_mode: no
  register: lynx_stat

- name: lynx
  tags: bar
  raw: "dnf install -y {{ lynx_el9 }}"
  become: true
  when:
   - not lynx_stat.stat.exists
   - ansible_os_family == 'RedHat'
   - ansible_distribution_major_version == '9'
